// Registry of the icons the backend may name: kebab name -> tabler component.
//
// Both backends that used to name icons from this set are gone (`research` group icons and
// `core_connectors` group icons, retired 2026-09-20), so today the registry is read only by the
// frontend itself. It is kept whole: it is the only place that turns such a name into something
// renderable, and the next backend that names an icon needs it intact. The imports are explicit
// on purpose:
// `@tabler/icons-vue` ships ~6000 components, so a runtime lookup over the whole package would
// pull all of them into the bundle and kill tree-shaking.
//
// A name outside the registry is not an error — no backend validates the stored value, so
// `iconByName()` falls back to a folder rather than rendering nothing.

import {
  IconFolder,
  IconAtom,
  IconMathFunction,
  IconMathPi,
  IconFlask,
  IconTestPipe,
  IconMicroscope,
  IconDna,
  IconVirus,
  IconVaccine,
  IconStethoscope,
  IconPlanet,
  IconSatellite,
  IconMountain,
  IconWorld,
  IconCode,
  IconTerminal2,
  IconGitBranch,
  IconBug,
  IconRobot,
  IconBinaryTree,
  IconDatabase,
  IconChartHistogram,
  IconChartPie,
  IconServer,
  IconCloudComputing,
  IconNetwork,
  IconShieldLock,
  IconKey,
  IconFingerprint,
  IconCpu,
  IconDeviceLaptop,
  IconBolt,
  IconBattery,
  IconSolarPanel,
  IconBuildingFactory2,
  IconCube,
  IconVectorBezier,
  IconRulerMeasure,
  IconGauge,
  IconScale,
  IconBriefcase,
  IconTargetArrow,
  IconPresentationAnalytics,
  IconCoins,
  IconPigMoney,
  IconBuildingBank,
  IconShoppingCart,
  IconBuildingStore,
  IconTag,
  IconSpeakerphone,
  IconGavel,
  IconLicense,
  IconSchool,
  IconBooks,
  IconNews,
  IconMicrophone,
  IconMessages,
  IconMail,
  IconPalette,
  IconBrush,
  IconMusic,
  IconCamera,
  IconFeather,
  IconNotebook,
  IconArticle,
  IconBuildingSkyscraper,
  IconHammer,
  IconCrane,
  IconTruckDelivery,
  IconShip,
  IconPlane,
  IconCompass,
  IconToolsKitchen2,
  IconWheat,
  IconTractor,
  IconBarbell,
  IconBallFootball,
  IconHome,
  IconTree,
  IconPaw,
  IconFlower,
  IconDeviceGamepad2,
  IconMasksTheater,
  IconUsersGroup,
  IconBuildingCastle,
  IconBox,
  IconFileText,
  IconNotes,
  IconBook2,
  IconBookmark,
  IconStar,
  IconFlag,
  IconPin,
  IconArchive,
  IconSearch,
  IconTelescope,
  IconBulb,
  IconBrain,
  IconPuzzle,
  IconTrophy,
  IconRocket,
  IconCalendar,
  IconClock,
  IconHourglass,
  IconRoute,
  IconTimeline,
  IconSitemap,
  IconTools,
  IconHexagon,
  IconDiamond,
  IconCloud,
  IconSun,
  IconMoodSmile,
  IconHeart,
  IconGridDots,
  IconLayersLinked,
  IconPackage,
  IconStack2,
  IconCategory
} from '@tabler/icons-vue'
import type { TablerIcon } from '@/shared/nav'

export const ICON_FALLBACK: TablerIcon = IconFolder

const ICONS: Record<string, TablerIcon> = {
  'atom': IconAtom,
  'math-function': IconMathFunction,
  'math-pi': IconMathPi,
  'flask': IconFlask,
  'test-pipe': IconTestPipe,
  'microscope': IconMicroscope,
  'dna': IconDna,
  'virus': IconVirus,
  'vaccine': IconVaccine,
  'stethoscope': IconStethoscope,
  'planet': IconPlanet,
  'satellite': IconSatellite,
  'mountain': IconMountain,
  'world': IconWorld,
  'code': IconCode,
  'terminal-2': IconTerminal2,
  'git-branch': IconGitBranch,
  'bug': IconBug,
  'robot': IconRobot,
  'binary-tree': IconBinaryTree,
  'database': IconDatabase,
  'chart-histogram': IconChartHistogram,
  'chart-pie': IconChartPie,
  'server': IconServer,
  'cloud-computing': IconCloudComputing,
  'network': IconNetwork,
  'shield-lock': IconShieldLock,
  'key': IconKey,
  'fingerprint': IconFingerprint,
  'cpu': IconCpu,
  'device-laptop': IconDeviceLaptop,
  'bolt': IconBolt,
  'battery': IconBattery,
  'solar-panel': IconSolarPanel,
  'building-factory-2': IconBuildingFactory2,
  'cube': IconCube,
  'vector-bezier': IconVectorBezier,
  'ruler-measure': IconRulerMeasure,
  'gauge': IconGauge,
  'scale': IconScale,
  'briefcase': IconBriefcase,
  'target-arrow': IconTargetArrow,
  'presentation-analytics': IconPresentationAnalytics,
  'coins': IconCoins,
  'pig-money': IconPigMoney,
  'building-bank': IconBuildingBank,
  'shopping-cart': IconShoppingCart,
  'building-store': IconBuildingStore,
  'tag': IconTag,
  'speakerphone': IconSpeakerphone,
  'gavel': IconGavel,
  'license': IconLicense,
  'school': IconSchool,
  'books': IconBooks,
  'news': IconNews,
  'microphone': IconMicrophone,
  'messages': IconMessages,
  'mail': IconMail,
  'palette': IconPalette,
  'brush': IconBrush,
  'music': IconMusic,
  'camera': IconCamera,
  'feather': IconFeather,
  'notebook': IconNotebook,
  'article': IconArticle,
  'building-skyscraper': IconBuildingSkyscraper,
  'hammer': IconHammer,
  'crane': IconCrane,
  'truck-delivery': IconTruckDelivery,
  'ship': IconShip,
  'plane': IconPlane,
  'compass': IconCompass,
  'tools-kitchen-2': IconToolsKitchen2,
  'wheat': IconWheat,
  'tractor': IconTractor,
  'barbell': IconBarbell,
  'ball-football': IconBallFootball,
  'home': IconHome,
  'tree': IconTree,
  'paw': IconPaw,
  'flower': IconFlower,
  'device-gamepad-2': IconDeviceGamepad2,
  'masks-theater': IconMasksTheater,
  'users-group': IconUsersGroup,
  'building-castle': IconBuildingCastle,
  'folder': IconFolder,
  'box': IconBox,
  'file-text': IconFileText,
  'notes': IconNotes,
  'book-2': IconBook2,
  'bookmark': IconBookmark,
  'star': IconStar,
  'flag': IconFlag,
  'pin': IconPin,
  'archive': IconArchive,
  'search': IconSearch,
  'telescope': IconTelescope,
  'bulb': IconBulb,
  'brain': IconBrain,
  'puzzle': IconPuzzle,
  'trophy': IconTrophy,
  'rocket': IconRocket,
  'calendar': IconCalendar,
  'clock': IconClock,
  'hourglass': IconHourglass,
  'route': IconRoute,
  'timeline': IconTimeline,
  'sitemap': IconSitemap,
  'tools': IconTools,
  'hexagon': IconHexagon,
  'diamond': IconDiamond,
  'cloud': IconCloud,
  'sun': IconSun,
  'mood-smile': IconMoodSmile,
  'heart': IconHeart,
  'grid-dots': IconGridDots,
  'layers-linked': IconLayersLinked,
  'package': IconPackage,
  'stack-2': IconStack2,
  'category': IconCategory,
}

/** Icon component for a backend-named icon; unknown or empty -> the fallback. */
export function iconByName(name: string | null | undefined): TablerIcon {
  if (!name) return ICON_FALLBACK
  return ICONS[name] ?? ICON_FALLBACK
}

/** Every name the picker may offer, in the order the backend lists them. */
export function iconNames(): string[] {
  return Object.keys(ICONS)
}
